# Generated by Django 4.2.1 on 2023-05-13 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_grouppost'),
        ('home', '0010_post_favorited_by_favorite'),
    ]

    operations = [
    ]
